### PR TITLE
replace write command with a NOTE

### LINKED ISSUE #290: AM5OM4 coupled experiment fails in debug mode
**Describe the bug**
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/3b584df526ee68975a764789f96fab7056e4e122/driver/GFDL/atmosphere.F90#L209

The above lines fails in the debug mode with AM5_OM4 coupled model with the following coupler.res
```
    4        (Calendar: no_calendar=0, thirty_day_months=1, julian=2, gregorian=3, noleap=4)
     1     1     1     0     0     0        Model start time:   year, month, day, hour, minute, second
   101     1     1     0     0     0        Current model time: year, month, day, hour, minute, second
```

This is because the number of seconds is very large and it won't fit in an f9.1 format. We also shouldn't be hard coding 0 as the unit number. 

/lustre/f2/scratch/Uriel.Ramirez/am5/am5f3b1r1/c384L65_am5f3b1r1_OM4_p25_piControl_noBLING_DynVeg/ncrc5.intel23-classic-debug-openmp/stdout/run/c384L65_am5f3b1r1_OM4_p25_piControl_noBLING_DynVeg_1x0m2d_3456x4a_1002x1o1.o134581235
```
atmosphere_init: current_time_seconds = *********
forrtl: error (63): output conversion error, unit 0, file /proc/65909/fd/2
Image              PC                Routine            Line        Source            

Stack trace terminated abnormally.
```
**To Reproduce**
Run the c384L65_am5f3b1r1_OM4_p25_piControl_noBLING_DynVeg experiment in debug mode:
https://gitlab.gfdl.noaa.gov/m5/am5xml/-/blob/main/am5.xml?ref_type=heads#L188

**Expected behavior**
That should not fail

**System Environment**
Describe the system environment, include:
Intel23-classic on gaeac5 in debug mode

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
replaces a write command with a NOTE
Fixes #290 

**How Has This Been Tested?**
This was tested with the coupled AM5_OM4 model in debug mode

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by bensonr — APPROVED** [review]
Thanks @uramirez8707

**Review by laurenchilutti — APPROVED** [review]

**Comment by laurenchilutti** [comment]
@lharris4 commented on the Issue that this write statement may no longer be necessary.  Should I merge this change in or should @uramirez8707 remove this write statement instead?

**Comment by lharris4** [comment]
Hi, @laurenchilutti . Let's remove the write statement.

Thanks,
Lucas

**Comment by uramirez8707** [comment]
@lharris4 I removed the write statement

**Review by lharris4 — APPROVED** [review]

**Comment by lharris4** [comment]
I prefer this solution. Thank you.

**Review by laurenchilutti — APPROVED** [review]

**Review by bensonr — APPROVED** [review]

**Pull request merged**
