### PR TITLE
Rename CCPP_interstitial (to GFDL_interstitial?)

### PR DESCRIPTION
**Pull request by climbfuji**
**Description**

I would like to rename `CCPP_interstitial` into something more meaningful for the fv3atm atmospheric model. The term is confusing, because fv3atm has `GFS_interstitial` for the GFS (slow/traditional physics), and `CCPP_interstitial` for the FV3 dycore (fast/tightly coupled physics). Both of them are interstitial data types required by CCPP and they are defined in a module called `CCPP_typedefs.F90`.

For now, I changed it to `GFDL_interstitial` but I am not 100% happy with this name and I would welcome suggestions for a better name. This PR shows the small extent of these changes.

Related, I would like to consider renaming the CCPP variable `cdata_tile` to something more meaningful, for example `cdata_dycore`? There are two other `cdata` variables in fv3atm, `cdata_block` (when blocked data is passed) and `cdata_domain` (when all blocks are passed as one contiguous data).

Fixes https://github.com/NOAA-EMC/fv3atm/issues/507.

**How Has This Been Tested?**

Tested with the ufs-weather-model regression tests, see https://github.com/ufs-community/ufs-weather-model/pull/1130

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by climbfuji** [comment]
@junwang-noaa @bensonr Would you be able to give me some feedback on the proposed name change for the CCPP interstitial data container? Thanks very much!

**Comment by junwang-noaa** [comment]
I am thinking maybe slowPhys_interstitial and fastPhys_interstitial? It's not clear to me what GFS_interestitial and GFDL_insterstitial means.

Also I agree cdata_dycore is the data used in dycore, it's easier to understand then cdata_tile.

**Comment by lharris4** [comment]
Hi, Dom. So ccpp_associate is some sort of dynamic data type?

Thanks,
Lucas

**Comment by climbfuji** [comment]
Ahhhh, no, that’s just a label for the “associate" statement like you can do for “if”, “do” etc.

**Comment by lharris4** [comment]
OK. Thanks.

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@laurenchilutti We are now working on Dom's PR, may I ask if this PR is ready for commit?

**Review by bensonr — APPROVED** [review]

**Comment by laurenchilutti** [comment]
@junwang-noaa This PR is now ready for commit.

**Comment by climbfuji** [comment]
Thanks for the reviews. Please merge this PR, regression testing is complete.

**Pull request merged**
