### PR TITLE
allocate heat_source when SKEB is True and  d_con is zero

### PR DESCRIPTION
**Pull request by NeilBarton-NOAA**
**Description**

The model fails when d_con is zero and skeb is True because heat_source is unallocated. This change allocates heat_source when skeb is True

Fixes # (issue)

No issue previously assigned. 

**How Has This Been Tested?**

The code has been tested in the gefs forecasting in g-w. Currently testing rt.

**Checklist:**

Please check all whether they apply or not
- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by XiaqiongZhou-NOAA — APPROVED** [review]

**Review by lharris4 — APPROVED** [review]
Looks good to me. Thanks for submitting this change.

**Review by bensonr — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
#[2278](https://github.com/ufs-community/ufs-weather-model/pull/2278) is ready, please continue with the merge process, thank you.

**Comment by bensonr** [comment]
@NeilBarton-NOAA - Did you create an issue for this PR?  I want to make sure it gets closed.

**Comment by NeilBarton-NOAA** [comment]
@bensonr I did not.

**Pull request merged**
