### PR TITLE
Fixes to run 32BIT MULTI_GASES 

### PR DESCRIPTION
**Pull request by XiaqiongZhou-NOAA**
To fix the compiling error with 32BIT and MULTI_GASES =Y

Related pull requests
https://github.com/ufs-community/ufs-weather-model/pull/112
https://github.com/NOAA-EMC/fv3atm/pull/108
https://github.com/NCAR/ccpp-physics/pull/444

### CODE REVIEW

**Comment by bensonr** [comment]
@XiaqiongZhou-NOAA I think you want this pull request to go to NOAA-EMC::dev/emc first.

**Comment by XiaqiongZhou-NOAA** [comment]
I will correct it.

**Comment by lharris4** [comment]
Hi, Kate. Has the dry mass problem from the IAU been fixed yet without
needing the mass fixer?

Lucas

**Comment by XiaqiongZhou-NOAA** [comment]
Lucas:
I am sorry I do not know the final solution about how to fix the dry mass
problem from the IAU .
Fangling should know better about .

By the way, I have closed the wrong pull request to GFDL Dynamic code and
changed to the EMC fork.

Best
Kate

**Comment by junwang-noaa** [comment]
Lucas, my understanding is that we are using adjust_dry_mass from
fv3_dycore for iau run in GFS.v16, and the problem is resolved. We donot
use the iau mass fixer

**Pull request closed without merging**
