### PR TITLE
ufs-release/public-v2: cherry-pick add GFSv16 dzmin change and changes for Dev/jcsda

### PR DESCRIPTION
**Pull request by llpcarson**
* add GFSv16 dzmin change
* Add code changes in external_ic.F90 and fv_grid_tools.F90 for dev/jcsda

https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/44

Related PRs:
fv3atm: https://github.com/NOAA-EMC/fv3atm/pull/223
ufs-weather-model: https://github.com/ufs-community/ufs-weather-model/pull/356

### CODE REVIEW

**Comment by junwang-noaa** [comment]
I am not sure why those changes are picked for release v2. My understanding is that the dzmin is a temporary fix for GFSv16, and the release v2 is for regional application, is there a stability issue in regional application? The two other code changes are for ongoing JEDI development, since more changes are coming and may be required for DA, I'd suggest people to go to dev/emc branch if they want to try DA application, rather than the release branch.

**Comment by climbfuji** [comment]
> I am not sure why those changes are picked for release v2. My understanding is that the dzmin is a temporary fix for GFSv16, and the release v2 is for regional application, is there a stability issue in regional application? The two other code changes are for ongoing JEDI development, since more changes are coming and may be required for DA, I'd suggest people to go to dev/emc branch if they want to try DA application, rather than the release branch.

I think we need to ask @JeffBeck-NOAA and @jwolff-ncar, or at least they know whom to contact regarding the motivation for this PR.

**Comment by llpcarson** [comment]
Hi Jun - Jacob Carley has been running his real-time parallel regional model with this change (dz_min) and finds the model is more stable.  I cherry-picked the combined commit that included the jcsda changes, to simplify the git commit history.  These are not required for the release branch, but were committed to develop together.

**Comment by jwolff-ncar** [comment]
This cherry-picked addition to the release branch was at the request of @JacobCarley-NOAA based on his experience with regional runs.

**Comment by bensonr** [comment]
@junwang-noaa @laurenchilutti - can you guys provide a formal review.

**Comment by bensonr** [comment]
If the reason for the updates is satisfactory to everyone, I can finish up the merge once I have formal reviews.

**Comment by lharris4** [comment]
Hi, all. The fix is OK for now, but an issue needs to be opened indicating
the need for a long-term, more fundamental fix, noting the objections that @Xi
Chen - NOAA Affiliate <xi.chen@noaa.gov> and I have raised. The solution
lies in changes to the topography filtering for certain small islands or
peninsulas, and/or in fixes to the physics: previously the GWD was causing
crashes for us, and more recently @Kai-Yuan Cheng - NOAA Affiliate
<kai-yuan.cheng@noaa.gov> has found strange behavior in the deep convection
scheme causing a similar crash.

Lucas

**Comment by lharris4** [comment]
Upon further review, the change to dz_min is fine but I have severe
concerns about changing gz(km+1), which is the surface topography height.
This does not change phis, the saved, static topography (to the best of my
knowledge) but it could yield inconsistencies and noisy solutions. In
particular when running at convective scales someone needs to check closely
the behavior of w close to topography, especially steep marginally-resolved
topography.

Lucas

**Comment by lharris4** [comment]
Also what is the rationale for the changes in fv_grid_tools.F90 ?

**Comment by junwang-noaa** [comment]
Lucas, the changes in fv_grid_tools.F90  are required for DA, please see issue
#32 <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/issues/32>

**Comment by lharris4** [comment]
Hi, Jun. Thanks. This makes more sense now, and removing the hard-coded
filename is something I have wanted to do for a while now.

**Comment by JacobCarley-NOAA** [comment]
> Upon further review, the change to dz_min is fine but I have severe concerns about changing gz(km+1), which is the surface topography height. This does not change phis, the saved, static topography (to the best of my knowledge) but it could yield inconsistencies and noisy solutions. In particular when running at convective scales someone needs to check closely the behavior of w close to topography, especially steep marginally-resolved topography. Lucas On Mon, Jan 11, 2021 at 1:32 PM Lucas Harris - NOAA Federal < lucas.harris@noaa.gov> wrote:


Kate Zhou (@XiaqiongZhou-NOAA, xiaqiong.zhou@noaa.gov) may know more about this.

**Comment by XiaqiongZhou-NOAA** [comment]
In the higher resolution regional runs, dz_min=6 is also a rare situation as in GFSv16. 
This is a temporary fix for some crashes. This change actually prevents extreme large downdrafts and updrafts that finally cause model crashes even there are inconsistencies.
   
In addition, the regional group also found there were many extreme warm temperature warning in their runs as Kai-Yuan found. It can not be solved with the dz_min fix. They are related physics tendencies. It is a different issue that has to be investigated.

**Comment by climbfuji** [comment]
All, have we come to a conclusion about this PR for the SRW App release?

**Comment by junwang-noaa** [comment]
I'd refer to @JacobCarley-NOAA for approval as I am not sure if the changes are required to be included in public release-v2.

**Comment by JacobCarley-NOAA** [comment]
I'm good with this is those concerns expressed by @lharris4 were covered by comments from @XiaqiongZhou-NOAA .

**Review by junwang-noaa — APPROVED** [review]
Jacob confirmed the code changes are required for release public_v2.

**Comment by lharris4** [comment]
Hi, all. Thanks. I think it would be good if an issue were opened up
regarding the temporary nature of this fix.

Lucas

**Comment by llpcarson** [comment]
I opened a new issue, and referenced the discussion in this PR.

**Comment by lharris4** [comment]
Thanks :-)

**Review by bensonr — APPROVED** [review]

**Review by laurenchilutti — APPROVED** [review]

**Pull request merged**
