### PR TITLE
Updates for example notebook directory

### PR DESCRIPTION
**Pull request by lharris4**
**Description**

Expands the number of available example notebooks with new idealized cases. Also includes updates for 

Fixes # (n/a)

**How Has This Been Tested?**

n/a

**Checklist:**

Please check all whether they apply or not
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lharris4** [comment]
About conflicts: the conflicting files are total replacements for those already in the repository.

**Comment by lharris4** [comment]
@bensonr I would like to have this merged before my talk at the SRW training tomorrow. The two conflicting files are complete replacements for the existing files. Is there anything else I need to do to be able to finish this merge?

Thanks,
Lucas

**Comment by bensonr** [comment]
@lharris4 - apologies for not getting to this sooner.  I can't merge this until the conflicts are resolved.  I will take a look and see what can be done.

**Comment by bensonr** [comment]
Superseded by #144

**Pull request closed without merging**
