### PR TITLE
New notebooks

### PR DESCRIPTION
**Pull request by lharris4**
**Description**

Two new Python notebooks:
- Interactive notebook, `FV3_level_transmogrifier`, which shows different FV3 standard levels and allows inspection for discontinuities. Directory has the dependent files including the standard atmosphere and a Linux-Intel binary for fv_eta_mod. This allows construction of new vertical level setups that are free of noise and stability issues.
- Held-Suarez Zurita-Gotor superrotation notebook (one more thing some people said FV3 couldn't do...) 

**How Has This Been Tested?**

Not code, just Python notebooks.

**Checklist:**

Please check all whether they apply or not
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by bensonr — COMMENTED** [review]
I know this is a small file, but does fv_eta.cpython-39-x86_64-linux-gnu.so need to be stored in the repo?

**Comment by lharris4** [comment]
Hi, Rusty. Users could conceivably simply compile the Python-wrapped
library themselves (instructions are in fv_eta.F90) so if it doesn't belong
there we can remove it.

Thanks,
Lucas

**Comment by bensonr** [comment]
@lharris4 - I think we'd have a better git experience without the python compiled object in the repository.

**Comment by lharris4** [comment]
OK. I have a few updates I want to make anyway so hold off on the PR.

Thanks,
Lucas

**Comment by lharris4** [comment]
OK, I have made some updates, deleted the binary, and added instructions for re-creating the binary containing the wrapped fv_eta module.

**Review by laurenchilutti — APPROVED** [review]

**Comment by lharris4** [comment]
Hi, Lauren. Thanks for taking care of this.

Lucas

**Pull request merged**
