### PR TITLE
nesting bug fixes for uninitialized variable in fv3 and incorrect tile number in fv3atm

### LINKED ISSUE #328: hailwat tracer index is uninitialized in setup_pt_NH_BC
**Describe the bug**
In `subroutine setup_pt_NH_BC` within `fv_nesting.F90`, you will find this code:

```f90
   integer :: liq_wat, ice_wat, rainwat, snowwat, graupel, hailwat
...
   liq_wat = get_tracer_index (MODEL_ATMOS, 'liq_wat')
   ice_wat = get_tracer_index (MODEL_ATMOS, 'ice_wat')
   rainwat = get_tracer_index (MODEL_ATMOS, 'rainwat')
   snowwat = get_tracer_index (MODEL_ATMOS, 'snowwat')
   graupel = get_tracer_index (MODEL_ATMOS, 'graupel')

...
   if (hailwat > 0) then
      hailwatBC_west  => q_BC(hailwat)%west_t1
      hailwatBC_east  => q_BC(hailwat)%east_t1
      hailwatBC_north => q_BC(hailwat)%north_t1
      hailwatBC_south => q_BC(hailwat)%south_t1
   else
      hailwatBC_west  => dum_west
      hailwatBC_east  => dum_east
      hailwatBC_north => dum_north
      hailwatBC_south => dum_south
   endif
```

Notice the hailwat is never initialized.

I suspect the correct solution is to add this line:

```f90
   hailwat = get_tracer_index (MODEL_ATMOS, 'hailwat')
```

**To Reproduce**
There is no straightforward way to reproduce this behavior at runtime, but it is obvious from the code.

**Expected behavior**
Variables should be initialized and array indexes should be correct.

**System Environment**
N/A - the error is plainly visible in the source code

**Additional context**
N/A

### LINKED ISSUE #329: fv3atm needs the global_tile from atmosphere_control_data so CCPP can read per-tile static files
**Is your feature request related to a problem? Please describe.**
Additional information is here:

https://github.com/NOAA-EMC/fv3atm/issues/797

In the fv3atm, some CCPP physics schemes read per-tile static files. With a global simulation that has a single static nest (tile 7) the nest will read tile 1, which is the first global tile. This is because the model is using tile_of_mosaic instead of global_tile.

**Describe the solution you'd like**
The `atmosphere_control_data` should be able to provide the global_tile.

<details> <summary>Suggested Solution</summary>

In addition to relevant model-level changes:

```diff
diff --git a/driver/fvGFS/atmosphere.F90 b/driver/fvGFS/atmosphere.F90
index dcd43fb..a718b95 100644
--- a/driver/fvGFS/atmosphere.F90
+++ b/driver/fvGFS/atmosphere.F90
@@ -864,17 +864,18 @@ contains
  end subroutine atmosphere_pref
 
 
- subroutine atmosphere_control_data (i1, i2, j1, j2, kt, p_hydro, hydro, tile_num)
+ subroutine atmosphere_control_data (i1, i2, j1, j2, kt, p_hydro, hydro, tile_of_mosaic, global_tile_num)
    integer, intent(out)           :: i1, i2, j1, j2, kt
    logical, intent(out), optional :: p_hydro, hydro
-   integer, intent(out), optional :: tile_num
+   integer, intent(out), optional :: tile_of_mosaic, global_tile_num
    i1 = Atm(mygrid)%bd%isc
    i2 = Atm(mygrid)%bd%iec
    j1 = Atm(mygrid)%bd%jsc
    j2 = Atm(mygrid)%bd%jec
    kt = Atm(mygrid)%npz
 
-   if (present(tile_num)) tile_num = Atm(mygrid)%tile_of_mosaic
+   if (present(global_tile_num)) global_tile_num = Atm(mygrid)%global_tile
+   if (present(tile_of_mosaic)) tile_of_mosaic = Atm(mygrid)%tile_of_mosaic
    if (present(p_hydro)) p_hydro   = Atm(mygrid)%flagstruct%phys_hydrostatic
    if (present(  hydro))   hydro   = Atm(mygrid)%flagstruct%hydrostatic
```

</details>

**Describe alternatives you've considered**
Can't think of any.

**Additional context**
This is for the Water in the West project, which aims to have a static nest over the north-east pacific within a global model.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
**Description**

This fixes #328 by initializing the hailwat variable to the hailwat tracer index.
It fixes #329 by allowing the caller to request either the global_tile or tile_in_mosaic.

- fixes #328
- fixes #329

**How Has This Been Tested?**

1. Running the test case that failed. It's a rotated cube sphere with a large static nest, using GFS physics
2. Running regression tests on Hera CentOS

The Hera Rocky tests await bug fixes to the regression tests which should be available this week.

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by bensonr — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Review by XiaqiongZhou-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
@bensonr testing is complete on UFS-WM PR #2201. Can you please merge this PR for us?

**Comment by bensonr** [comment]
Can you confirm this has the top of the dev/emc trunk merged in?  Tagging @jkbk2004 @junwang-noaa @DusanJovic-NOAA to be sure.

**Comment by SamuelTrahanNOAA** [comment]
The "git merge" command thinks it is up to date:

```
[ =129 19:15:22 100671 Samuel.Trahan@hfe10 ]
.../Samuel.Trahan/westwater/nesting-fixes/FV3/atmos_cubed_sphere> git fetch --all
Fetching sam
Fetching upstream
remote: Enumerating objects: 498, done.
remote: Counting objects: 100% (379/379), done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 498 (delta 257), reused 258 (delta 203), pack-reused 119
Receiving objects: 100% (498/498), 4.11 MiB | 22.77 MiB/s, done.
Resolving deltas: 100% (292/292), completed with 53 local objects.
From https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere
 * [new branch]      autotools.build       -> upstream/autotools.build
 * [new branch]      dev/emc               -> upstream/dev/emc
 * [new branch]      dev/gfdl              -> upstream/dev/gfdl
 * [new branch]      dev/gfdl_am5          -> upstream/dev/gfdl_am5
 * [new branch]      dev/gfdl_am5_test     -> upstream/dev/gfdl_am5_test
 * [new branch]      main                  -> upstream/main
 * [new branch]      ufs-release/public-v1 -> upstream/ufs-release/public-v1
 * [new branch]      ufs-release/public-v2 -> upstream/ufs-release/public-v2
 * [new tag]         2023.03_am5           -> 2023.03_am5
 * [new tag]         ufs-srw-v2.0.0        -> ufs-srw-v2.0.0
 * [new tag]         2022.03               -> 2022.03
 * [new tag]         2022.04               -> 2022.04
 * [new tag]         2023.01               -> 2023.01
 * [new tag]         2023.01_am5           -> 2023.01_am5
 * [new tag]         2023.02               -> 2023.02
 * [new tag]         2023.02-alpha1        -> 2023.02-alpha1
 * [new tag]         2023.02_am5           -> 2023.02_am5
 * [new tag]         2023.03               -> 2023.03
 * [new tag]         2023.03-beta1         -> 2023.03-beta1
 * [new tag]         2023.03-beta1_am5     -> 2023.03-beta1_am5
 * [new tag]         FV3-202210-public     -> FV3-202210-public
 * [new tag]         FV3-202305-public     -> FV3-202305-public
[ =0 19:15:29 100672 Samuel.Trahan@hfe10 ]
.../Samuel.Trahan/westwater/nesting-fixes/FV3/atmos_cubed_sphere> git merge upstream/dev/emc
Already up to date.
[ =0 19:15:46 100673 Samuel.Trahan@hfe10 ]
.../Samuel.Trahan/westwater/nesting-fixes/FV3/atmos_cubed_sphere> git remote get-url upstream
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere

```

**Comment by jkbk2004** [comment]
@bensonr https://github.com/ufs-community/ufs-weather-model/actions/runs/8666708764/job/23768118824. All good to merge this pr.

**Pull request merged**
