### PR TITLE
Update RELEASE.md with tech note pointer

### PR DESCRIPTION
**Pull request by bensonr**
Also removed trailing whitespace and tab characters from all source files.

### CODE REVIEW

**Comment by bensonr** [comment]
@lharris4 - could you please review this pull request to NOAA-GFDL/GFDL_atmos_cubed_sphere?

**Comment by lharris4** [comment]
Hi, Rusty. Thanks. It looks good. The only additional change (which was
caught by Kate) that I forgot to upload was to change the default value of
nestupdate in fv_array.F90 from 0 to 7.

Lucas

**Comment by bensonr** [comment]
@lharris4 - the default value of nestupdate is now 7.  If there are no other updates, I'll merge these changes into master and update the release tag.

**Comment by lharris4** [comment]
Hi, Rusty. I think that is all.

Thanks for your help.

Lucas

**Pull request merged**
