### PR TITLE
build the dycore with cmake

### LINKED ISSUE #139: Keep build and source code together for the dynamical core (atleast for dev/emc)
**Is your feature request related to a problem? Please describe.**
Currently, the build and the source code of the FV3 dynamical core reside in two different repositories.

NOAA's UFS uses a universal CMake build system and maintains a build framework for the UFS-weather-model.
`dev/emc` branch in this repository contains the source code for use with the UFS-weather-model.

**Describe the solution you'd like**
Maintain build and source code for the dynamical core of the FV3 together.

**Additional context**
This was discussed with @bensonr in a series of emails around 7/19/2021.  Here is the relevant outcome from that discussion:

> Hi Rahul,
> 
> As dev/emc exists for use within GFS/UFS, contributing a CMake build system would be appropriate.  The FV3 team at GFDL can then decide whether to include (git cherry-pick) this in the master/main branch for their own use with the SHiELD model.
> 
> thanks - Rusty

### PR DESCRIPTION
**Pull request by aerorahul**
**Description**

The build and the source code for the FV3 dynamical core resides in two different repositories, which is less than ideal.

This PR:
- includes a `CMake` build for the dynamical core intended for the UFS and thus the PR is to merge into `dev/emc`

This is an excerpt from an email with @bensonr from 7/19/2021

> Hi Rahul,
> 
> As dev/emc exists for use within GFS/UFS, contributing a CMake build system would be appropriate.  The FV3 team at GFDL can then decide whether to include (git cherry-pick) this in the master/main branch for their own use with the SHiELD model.
> 
> thanks - Rusty

Fixes #139 

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration (e.g. compiler, OS).  Include
enough information so someone can reproduce your tests.

Testing is in progress with UFS-weather-model.
Note that this PR does not have any impact on current UFS-weather-model.
A subsequent change in the UFS-weather-model will remove the FV3 dynamical core build from FV3atm at which point these changes will come in play.

**Checklist:**

Please check all whether they apply or not
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by bensonr** [comment]
@aerorahul - who all would you recommend for reviews?

**Comment by aerorahul** [comment]
> @aerorahul - who all would you recommend for reviews?

@DusanJovic-NOAA @climbfuji

**Review by DomHeinzeller — COMMENTED** [review]
This is not for this PR, but for the future. We have so many repositories that use `FindNetCDF.cmake` and `FindESMF.cmake`. Should we strive for using one submodule like `CMakeModules` for this, or even better, is there a way to include those in the official `CMake` distributions?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by climbfuji — CHANGES_REQUESTED** [review]
This PR as-is changed the regression test results for the AWS CI tests and on Jet with Intel for yet unknown reasons.

**Comment by aerorahul** [comment]
The atm dycore is handled differently than other components in the UFS.
Isolating and fixing this issue will likely result in non-reproducible baseline due to this special handling.

**Comment by aerorahul** [comment]
reopening this PR.
Merging this PR without changes in the fv3atm will not impact UFS weather model as fv3atm provides the build.
The compiler flags can be fine tuned at a later time when fv3atm is cleaned up to use this functionality.

**Comment by DusanJovic-NOAA** [comment]
Having the CMakeLists.txt in this repo but not using it in UFS just creates confusion. And is maintenance burden, because now the same change has to be applied at two places.

**Review by DomHeinzeller — COMMENTED** [review]
I don't see the merit of merging this now. It just pushes the burden to fix this to "someone else" at "some point later". We would be merging code that we know is not correct (w.r.t. b4b regression testing in the UFS) and it won't be tested. If this code is urgently needed, it should be fixed now and then merged, unless we agree that we don't care about getting the same results or not.

**Comment by DusanJovic-NOAA** [comment]
Here's my suggestion. What if we remove setting compiler flags from this CMakeLists.txt and have them inherited from the upper levels of the app, as we do with other parts of the UFS, like fv3atm, or stochastic physics, etc.

**Comment by climbfuji** [comment]
> Here's my suggestion. What if we remove setting compiler flags from this CMakeLists.txt and have them inherited from the upper levels of the app, as we do with other parts of the UFS, like fv3atm, or stochastic physics, etc.

I like that idea. Is there a smart way to detect if build flags are set by a parent cmake config, or whether this is a standalone build (in which default build flags can be configured)? I'd be interested in such a solution, because it would greatly simplify the existing CCPP `CMakeLists.txt` files.

**Comment by aerorahul** [comment]
We could do something like this on Line 163 of `CMakeLists.txt`
```
if(NOT UFS)
  include(fv3_compiler_flags)
endif()

**Comment by climbfuji** [comment]
> We could do something like this on Line 163 of `CMakeLists.txt`
> 
> ```
> if(NOT UFS)
>   include(fv3_compiler_flags)
> endif()
> ```

I was thinking along checking if a CMake project has been defined already. The top-level ufs-weather-model, for example, sets the following:
```
project(ufs
        VERSION 1.0
        LANGUAGES C CXX Fortran)
```
Would testing for `project` being defined be a suitable mechanism to detect a standalone build?

**Comment by aerorahul** [comment]
> > We could do something like this on Line 163 of `CMakeLists.txt`
> > ```
> > if(NOT UFS)
> >   include(fv3_compiler_flags)
> > endif()
> > ```
> 
> I was thinking along checking if a CMake project has been defined already. The top-level ufs-weather-model, for example, sets the following:
> 
> ```
> project(ufs
>         VERSION 1.0
>         LANGUAGES C CXX Fortran)
> ```
> 
> Would testing for `project` being defined be a suitable mechanism to detect a standalone build?

You can check on `project`, but this has to be just for the UFS as UFS is enforcing its flags.

**Comment by climbfuji** [comment]
> > > We could do something like this on Line 163 of `CMakeLists.txt`
> > > ```
> > > if(NOT UFS)
> > >   include(fv3_compiler_flags)
> > > endif()
> > > ```
> > 
> > 
> > I was thinking along checking if a CMake project has been defined already. The top-level ufs-weather-model, for example, sets the following:
> > ```
> > project(ufs
> >         VERSION 1.0
> >         LANGUAGES C CXX Fortran)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would testing for `project` being defined be a suitable mechanism to detect a standalone build?
> 
> You can check on `project`, but this has to be just for the UFS as UFS is enforcing its flags.

This is the question we have been debating for a while. Should components set their own flags, or should parents (of submodules) be in charge of setting those. It should be consistent, in my opinion.

**Comment by DusanJovic-NOAA** [comment]
Please remove `makefile` from the top-level directory. It's not used anymore.

**Comment by aerorahul** [comment]
> Please remove `makefile` from the top-level directory. It's not used anymore.

done.

**Review by climbfuji — APPROVED** [review]

**Review by DomHeinzeller — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
Ready for merge. @bensonr please merge this PR. All UFS tests passed. See https://github.com/ufs-community/ufs-weather-model/pull/812

**Pull request merged**
