### PR TITLE
code changes for addressing a regional lateral boundary condition issue

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
**Description**

Makes a change in regional lateral boundary condition (LBC) processing to prevent an unintended scenario that leads to the temporary usage of older wind values along the boundary immediately before fresh LBC information is ingested.  This change smooths out a transient spike in domain-averaged surface pressure tendency values seen at the frequency of LBC updates.

Fixes #(issue #169)

**How Has This Been Tested?**

The fix was initially tested using a canned UFS Short Range Weather App case (which with 6 h LBC updates was very sensitive to the problem being solved).  More recent testing was made using various UFS regression tests in the context of the latest UFS code.  The hafs_regional_atm test was the most scrutinized, as it was one of the few regional regression tests with both nrows_blend > 0 and a multi-hour LBC update frequency.   

The proposed fix changes answers for regional tests, but not for global tests.   All of the testing thus far has been made with Intel compiled code on various WCOSS platforms (WCOSS-cray, WCOSS-dellp3, WCOSS2). 

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lharris4 — APPROVED** [review]
This is the right way to implement this change. Thank you for making this modification to the code.

**Comment by junwang-noaa** [comment]
@laurenchilutti Matt created a ufs-weather-model PR[#1050](https://github.com/ufs-community/ufs-weather-model/pull/1050), is it OK we put the PR to the commit queue?

**Comment by laurenchilutti** [comment]
> @laurenchilutti Matt created a ufs-weather-model PR[#1050](https://github.com/ufs-community/ufs-weather-model/pull/1050), is it OK we put the PR to the commit queue?

@junwang-noaa What does adding this to the commit queue entail? We are still waiting for one more review to be complete.

**Comment by laurenchilutti** [comment]
> @laurenchilutti Putting the PR in the commit queue means the code is ready for commit, so it's better doing it after the reviewers approve the code changes. Some times final review is also needed at the code commit time when merge conflicts are resolved. Please let us know when the review is done. Thank you!

@junwang-noaa This PR is now ready to be added to the commit queue.  Please let me know when I can merge this.

**Comment by junwang-noaa** [comment]
Thanks, Lauren. The PR is added to the commit queue, the commit date is
planned on 2/22.

**Comment by junwang-noaa** [comment]
@laurenchilutti All the RT passed, would you please commit this PR? Thanks

**Pull request merged**
