### PR TITLE
Gzbugfix

### LINKED ISSUE #70: Problem with remapping?
This issue has been reported by @rheacangeo.

The remapping of v-component of the velocity in `fv_mapz.F90` might contain an error. At the call of `map1_ppm()` the index range `is:ie+1` is passed, see...
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/9078be0dfa50c94b65f5e2acff2d324ffe47aab4/model/fv_mapz.F90#L552-L554 

Internally the arguments `pe0`, `pe3` and `gz` are dimensioned with this index range, see...
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/9078be0dfa50c94b65f5e2acff2d324ffe47aab4/model/fv_mapz.F90#L1386-L1404

While this is ok for `pe0` and `pe3`, this is obviously not the correct dimensioning for the `gz` variable, see https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/9078be0dfa50c94b65f5e2acff2d324ffe47aab4/model/fv_mapz.F90#L157

### PR DESCRIPTION
**Pull request by JosephMouallem**
Description:

Increase the dimension of the local variable gz to have enough points needed when remapping v.
Adjust array bounds in the remapping routine and then compute the extra point only when it is needed from moist_cv before remapping v.

Fixes #70

**How Has This Been Tested?**

Tests were performed on Gaea with no answer change.
The modified code is affected with iv=-2 when calling map1_ppm. It works fine with iv=-2

**Checklist:**

Please check all whether they apply or not
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by JosephMouallem** [comment]
@bensonr @lharris4

**Review by lharris4 — APPROVED** [review]

**Review by lharris4 — APPROVED** [review]
Thank you for submitting this. This too should be brought into GitLab.

**Review by bensonr — APPROVED** [review]

**Review by laurenchilutti — APPROVED** [review]

**Comment by laurenchilutti** [comment]
I am merging this now and will be sure to bring this back to Gitlab and other branches.

**Comment by junwang-noaa** [comment]
@laurenchilutti may I ask if there is any plan to merge this bug fix to dev/emc branch? Thank

**Comment by laurenchilutti** [comment]
@junwang-noaa I can bring this over to dev/emc.  I would need assistance in testing and creating the fv3atm andufs-weather-model PRs as they require testing on systems I do not have allocation on. (I can only run on Gaea).

**Comment by junwang-noaa** [comment]
Sure, once you have a dycore branch from dev/emc with the changes, we can pick it up from there to test in ufs-weather-model. Thanks a lot!

**Pull request merged**
