### PR TITLE
202101 public release

### PR DESCRIPTION
**Pull request by laurenchilutti**
This pull request will publish the code changes developed by the FV3 Team at GFDL for the **202101 public release**.  See ```RELEASE.md``` for a description of the changes made in this PR.

### CODE REVIEW

**Review by lharris4 — APPROVED** [review]
looks fine to me.

**Review by bensonr — APPROVED** [review]

**Comment by laurenchilutti** [comment]
@bensonr @lharris4 I have pushed another commit to this release that updates driver/GFDL/atmosphere.F90 to resolve some differences between master and this release branch (mainly the release used the deprecated "mytile" as opposed to "mygrid").  This is ready to merge if the two of you still approve of the code.  Thank you!

**Comment by lharris4** [comment]
Hi, Lauren. Thanks for cleaning up the GFDL driver code. This looks good.

Are there still lingering differences between the FV3 code used for SHiELD
and AM4? I know that there is a change in the damping for one of the
dynamical variables in sw_core.F90 in SHiELD which is not being used in AM4.

Thanks,
Lucas

**Comment by bensonr** [comment]
@lharris4 @laurenchilutti - the one remaining difference is references to lin_cloud_microphysics in GFDL/AM4 version and gfdl_cloud_microphys in SHiELD.

**Review by bensonr — APPROVED** [review]

**Comment by lharris4** [comment]
Hi, Rusty. Thanks. This is OK for the time being.

Lucas

**Pull request merged**
