### PR TITLE
atmos_cubed_sphere

### PR DESCRIPTION
**Pull request by mlee03**
Updates dev/gfdl to internal xanadu tag

### CODE REVIEW

**Comment by thomas-robinson** [comment]
@uramirez8707 can you please test this with AM4 to make sure it reproduces answers and diagnostics?  Use am4p0 and am4p0_cmip6Diag

**Comment by uramirez8707** [comment]
@thomas-robinson check if it reproduces answers with xanadu, right?

**Comment by thomas-robinson** [comment]
Yes, it should reproduce xanadu

**Comment by uramirez8707** [comment]
@thomas-robinson @mlee03 restarts and diagnostics reproduce. I tried am4p0 and am4p0_cmip6Diag with intel 17 in debug, repro, and prod.

**Comment by mlee03** [comment]
@bensonr 
1.  All extraneous files have been deleted
2.  Model/fv_cmp.F90 has been reverted to its original version found in branch dev/gfdl
3.  All unnecessary comments have been removed from 
     tools/external_ic.F90 and    tools/fv_surf_map.F90

**Comment by thomas-robinson** [comment]
@bensonr I would recommend doing a merge and squash to a single commit for this PR.

**Pull request merged**
