### PR TITLE
Correct the jc index when print out the nest grid corner locations

### LINKED ISSUE #333: Typo/bug in fv_grid_tools.F90 in dev/emc branch when print out grid corner indexes and locations
**Describe the bug**
There is a typo/bug in [fv_grid_tools.F90](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/f060e857f184a4e8e988d8563794066525357336/tools/fv_grid_tools.F90#L2653C1-L2677C13) when print out the grid SW, NW, NE, SE CORNER indexes and lat/lon locations.
The source code lines of
ic = p_ind(1,1,1) ; jc = p_ind(1,1,1)
should be updated into:
ic = p_ind(1,1,1) ; jc = p_ind(1,1,2)
so that the jc gets the correct index. Otherwise, jc is always identical to ic, leading to wrong printout jc and lat/lon locations for the grid corners.

**Additional context**
This bug/typo was found/identified when checking UFS-HAFS moving-nesting forecast log. And you can see an proposed/example fix from this commit [4162fad](https://github.com/hafs-community/GFDL_atmos_cubed_sphere/commit/4162fad68d84db507bf25d4502673bc608c86600).

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
**Description**

This PR fixes a typo/bug when printing out the nest grid corner locations in tools/fv_grid_tools.F90.

Fixes #333 

Related ufs-weather-model PRs:

- NOAA-EMC/fv3atm/pull/847
- ufs-community/ufs-weather-model/pull/2323

**How Has This Been Tested?**
The fix has been tested in the HAFS application with ufs-weather-model.

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lharris4 — APPROVED** [review]

**Review by bensonr — APPROVED** [review]

**Review by XiaqiongZhou-NOAA — APPROVED** [review]

**Comment by lharris4** [comment]
@laurenchilutti should we go ahead and merge? BTW I would like to merge this into the main branch for the upcoming release.

**Comment by laurenchilutti** [comment]
We have to wait for the UFS code managers to give us the "OK" to merge PRs directed at the dev/emc branch.  
@BinLiu-NOAA have you created PRs in fv3atm and ufs-weather-model for this change?

**Comment by BinLiu-NOAA** [comment]
> We have to wait for the UFS code managers to give us the "OK" to merge PRs directed at the dev/emc branch. @BinLiu-NOAA have you created PRs in fv3atm and ufs-weather-model for this change?

@laurenchilutti I have created related PRs at FV3atm and ufs-weather-model levels. We can bring this up in tomorrow's UFS apps and components coordination meeting to discuss and coordinate on how to merge this series of PRs. Hopefully can be combined with another PR to speed up the process. Thanks!

**Comment by FernandoAndrade-NOAA** [comment]
Testing for #[2324](https://github.com/ufs-community/ufs-weather-model/pull/2324) is complete, please continue with merging this PR.

**Comment by FernandoAndrade-NOAA** [comment]
Correction - Please do not merge yet, there is still a missing commit on the WM side.

**Comment by FernandoAndrade-NOAA** [comment]
We should be all set here, sorry for any confusion!

**Pull request merged**
