### PR TITLE
Revert #302

### PR DESCRIPTION
**Pull request by spencerkclark**
**Description**

Per offline discussion with @lharris4, the fix made in #302 may not be scientifically correct.  This PR reverts that change for now, though reopens #301.

**How Has This Been Tested?**

There is not really an easy way to test this other than that the code compiles, which should be covered by CI.

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by bensonr — APPROVED** [review]

**Comment by bensonr** [comment]
@lharris4 - if you are okay with this, I'll merge it as soon as the checks finish.

**Comment by spencerkclark** [comment]
@bensonr, while I have you, could you go ahead and merge #316?  Thanks!

**Comment by bensonr** [comment]
@spencerkclark - if you'd like me to revert #302, I can simply press a button and it will take that change out.  I don't think we need a this PR.

**Review by lharris4 — APPROVED** [review]
I approve this change. I may need to take a closer look at what would be a better way to handle this.

**Pull request merged**
