### PR TITLE
Updates for fv_nudge code for ECDA work

### PR DESCRIPTION
**Pull request by wfcooke**
Adds latitudinal profile
Adds bas correction code
Adds diagnostics

Also edited to have 2 character indents rather than a nix of 2 and 3 characters indents in loops/if-statements

**How Has This Been Tested?**

Tested against previous results in short (8 - day) regression tests.

Potential issue for merging : Due to FMS I/O issues with other code, this is branching off 2022.03. I noticed there is a ptop argument that has been removed along the way to the latest version. Hopefully the automatic merger will catch and merge it appropriately.

**Checklist:**

Please check all whether they apply or not
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by bensonr** [comment]
@wfcooke - the merge will attempt to bring in the code and add the ptop back in to all of the interfaces.  Because of the mismatch in argument lists, the CI is failing.  You'll need to resubmit the file based on the current _main_.  Once that is done, we can cherry-pick it over to the _dev/gfdl_ and _dev/gfdl_am5_ branches for those running and developing the latest climate models at GFDL.

**Comment by wfcooke** [comment]
I updated the code and removed the ptop arguments.

**Review by bensonr — COMMENTED** [review]
I'm seeing the term _ada_ show up in your diagnostics.  Will this cause any confusion with the actual ada nudging system that is in the GFDL_tools directory?

**Comment by lharris4** [comment]
@wfcooke I am a little confused between all of the nudging methods myself. What is the meaning of 'ada' and how does it differ from the standard NWP nudging?

Lucas

**Comment by wfcooke** [comment]
I talked to Xiaosong and we think this was an oversight in copying a piece of code in from the ada code (related to slp).
'ada' has been updated to 'nudging'

**Comment by bensonr** [comment]
@wfcooke - does this mean we can officially retire fv_ada_nudge and get us down to supporting only the existing nwp_nudge and climate nudging?

**Comment by wfcooke** [comment]
I just sent around a note to my folks to get input on who is using what. 
I cannot speak for other divisions of course. 
Remind me in a few days if I don't respond.

**Comment by lharris4** [comment]
Hi, Will. Thanks for looking into this. It would be useful to know how
these different nudging codes are being used.

Lucas

**Comment by bensonr** [comment]
@lharris4 - we looked into it once before when there was a discussion about pruning them.  I'll search email and other places to see if I can find the discussion.

**Comment by wfcooke** [comment]
@lharris4 , @bensonr : I talked to my folks and from what I've heard, we are only using the fv_nwp_nudge setup.

**Comment by lharris4** [comment]
@wfcooke Thank you for checking. 

I checked with the chemistry folks, and they are using `climate_nudge` We can put a flag into `ada_nudge` to represent that it is being deprecated, and remove it in a later release.

**Review by lharris4 — APPROVED** [review]
@wfcooke coming back to this now. Thanks for adding these updates. Also thanks for adding the new diagnostics; keeping them contained within the nudging module is a good idea and I should do that for the other nudging tendencies too. I see no problems with these revisions.

**Review by bensonr — APPROVED** [review]

**Pull request merged**
